# Generated by Django 2.0.2 on 2021-12-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='year',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
