# Generated by Django 2.0.2 on 2021-12-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='notestype',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
